arm1:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001
arm2:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001