FASTbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_link_1
    pid: {p: 20000.0, i: 100, d: 70.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_link_2
    pid: {p: 15000.0, i: 250, d: 70.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_link_3
    pid: {p: 4500.0, i: 500, d: 70.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_link_4
    pid: {p: 3000.0, i: 50, d: 70.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_4_link_5
    pid: {p: 1000.0, i: 50, d: 70.0}
