# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  one_sia20d_joint_b:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_e:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_l:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_r:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_s:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_t:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
  one_sia20d_joint_u:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  one_wsg_finger_left_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  one_wsg_finger_right_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_b:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_e:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_l:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_r:
    has_velocity_limits: true
    max_velocity: 3.4906
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_s:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_t:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
  two_sia20d_joint_u:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  two_wsg_finger_left_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  two_wsg_finger_right_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0